spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  data:
    mongodb:
      uri: ${MONGO_ACTIVITY_URI}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: https://fitness-backend-1-3y57.onrender.com/eureka/

  instance:
    prefer-ip-address: true