spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  data:
    mongodb:
      uri: ${MONGO_AI_URI}
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: activity-processor-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.use.type.headers: false
#        spring.json.value.default.type: com.fitness.aiservice.model.Activity
#        spring.json.trusted.packages: "*"


#kafka:
#  topic:
#    name: activity-events

server:
  port: ${PORT:8080}


eureka:
  client:
    serviceUrl:
      defaultZone: https://fitness-backend-1-3y57.onrender.com/eureka/
  instance:
    prefer-ip-address: true


gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
    key: AIzaSyCRRm472RK86_HVSX9Z5_eddHQtO0IjhdE

